parameter_defaults:
  DnsServers: ['10.11.5.19']

  ControllerHostnameFormat: 'controller-%index%'
  ControllerSriovHostnameFormat: 'controller-%index%'
  ComputeSriovOffloadHostnameFormat: 'cmpt-offload-%index%'

  OvercloudControllerFlavor: "controller"
  OvercloudControllerSriovFlavor: "controller"
  OvercloudComputeFlavor: "compute"
  OvercloudComputeOvsDpdkFlavor: "compute"
  OvercloudComputeOvsDpdkSriovFlavor: "compute"
  OvercloudComputeSriovFlavor: "compute"
  OvercloudComputeSriovOffloadFlavor: "compute"

  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  ComputeOvsDpdkSriovHostnameFormat: 'computeovsdpdksriov-%index%'
  ComputeOvsDpdkSriovSchedulerHints:
    'capabilities:node': 'compute-%index%'

  ControllerCount: 0
  ControllerSriovCount: 3
  ComputeOvsDpdkSriovCount: 0
  ComputeOvsDpdkCount: 0
  ComputeVdpaCount: 1
  ComputeSriovCount: 1
  ComputeSriovOffloadCount: 0

  NtpServer: "clock.redhat.com"
  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'

  NtpPool: clock.corp.redhat.com
  MinPoll: 4
  MaxPoll: 5
