#Templates for 17.0 are specified with parameters instead of resource_registry mapping
---
resource_registry:
  # Set root password on overcloud nodes.
  OS::TripleO::NodeUserData: /usr/share/openstack-tripleo-heat-templates/firstboot/userdata_root_password.yaml

parameter_merge_strategies:
  ControllerSriovParameters: merge
  ComputeSriovParameters: merge

# Customize all these values to match the local environment
parameter_defaults:
  ComputeSriovNetworkConfigTemplate: '/home/stack/osp17_ref/nic-configs/computesriov.yaml'
  ControllerSriovNetworkConfigTemplate : '/home/stack/osp17_ref/nic-configs/controllersriov.yaml'

  # The tenant network type for Neutron (geneve).
  NeutronTunnelTypes: ""
  # The tenant network type for Neutron (vlan or geneve [8.2z needed]).
  NeutronNetworkType: "vlan"     #vDPA deploy guide
  # Enable DVR for deployment
  NeutronEnableDVR: false
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["10.46.0.31", "10.46.0.32"]
  # Nova flavor to use.

  #CloudDomain: localdomain

  # MTU global configuration
  NeutronGlobalPhysnetMtu: 9000
  # Configure the classname of the firewall driver to use for implementing security groups.
  NeutronOVSFirewallDriver: openvswitch
  SshServerOptions:
    UseDns: "no"
  # Enable log level DEBUG for supported components
  Debug: true

  ValidateGatewaysIcmp: false
  ValidateControllersIcmp: false

  ControllerSriovHostnameFormat: "controller-%index%"
  ControllerSriovSchedulerHints:
    "capabilities:node": "controller-%index%"
  ComputeSriovchedulerHints:
    "capabilities:node": "compute-%index%"

  EnableVLANTransparency: true

  # From Rocky live migration with NumaTopologyFilter disabled by default
  # https://bugs.launchpad.net/nova/+bug/1289064
  NovaEnableNUMALiveMigration: true
  NodeRootPassword: "12345678"

  ComputeSriovParameters:
    OvsHwOffload: true
    # Set OVN gateway router, required for external connectivity
    OVNCMSOptions: "enable-chassis-as-gw"
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on isolcpus=2-47,50-95"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-47,50-95"
    NovaComputeCpuDedicatedSet: ["2-47,50-95"]
    NovaReservedHostMemory: 4096
    NovaLibvirtRxQueueSize: 1024
    NovaLibvirtTxQueueSize: 1024
    NovaComputeCpuSharedSet: [0, 48, 1, 49]

    DerivePciWhitelistEnabled: false

  ############################
  #  Scheduler configuration #
  ############################
  NovaSchedulerDefaultFilters:
    - "RetryFilter"
    - "AvailabilityZoneFilter"
    - "ComputeFilter"
    - "ComputeCapabilitiesFilter"
    - "ImagePropertiesFilter"
    - "ServerGroupAntiAffinityFilter"
    - "ServerGroupAffinityFilter"
    - "PciPassthroughFilter"
    - "NUMATopologyFilter"
    - "AggregateInstanceExtraSpecsFilter"
