---
parameter_merge_strategies:
  ComputeSriovParameters: merge

#devname: "ens2f0np0" and "ens2f1np1"
parameter_defaults:
  ComputeSriovParameters:
    OvsHwOffload: true
    NovaPCIPassthrough:
      - vendor_id: "15b3"
        address: "0000:17:00.0"
        physical_network: "mx-network"
        trusted: "true"
        product_id: "101e"
      - vendor_id: "15b3"
        address: "0000:17:00.1"
        physical_network:  "mx-network"
        trusted: "true"
        product_id: "101e"
