---
parameter_merge_strategies:
   ComputeVdpaParameters: merge

parameter_defaults:
   ComputeVdpaNetworkConfigTemplate: '/home/stack/osp17_ref/nic-configs/computevdpa.yaml'

   # In the future, most parameters will be derived by mistral plan.
   ComputeVdpaParameters:
     OvsHwOffload: true
     OVNCMSOptions: "enable-chassis-as-gw"
     KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on isolcpus=2-47,50-95"
     TunedProfileName: "cpu-partitioning"
     IsolCpusList: "2-47,50-95"
     NovaComputeCpuDedicatedSet: ["2-47,50-95"]
     NovaReservedHostMemory: 4096
     NovaLibvirtRxQueueSize: 1024
     NovaLibvirtTxQueueSize: 1024
     NovaComputeCpuSharedSet: [0, 48, 1, 49]

     NovaPCIPassthrough:
      - vendor_id: "15b3"
        product_id: "101e" #VF product id(0xa2d6) (VF is 101e)
        address: "0000:17:00.0"
        physical_network: mx-network
        trusted: "true"
      - vendor_id: "15b3"
        product_id: "101e" #This is VF product id (PF is 101e)
        address: "0000:17:00.1"
        physical_network: mx-network
        trusted: "true"

     DerivePciWhitelistEnabled: false

  ############################
  #  Scheduler configuration #
  ############################
   NovaSchedulerDefaultFilters:
     - "RetryFilter"
     - "AvailabilityZoneFilter"
     - "ComputeFilter"
     - "ComputeCapabilitiesFilter"
     - "ImagePropertiesFilter"
     - "ServerGroupAntiAffinityFilter"
     - "ServerGroupAffinityFilter"
     - "PciPassthroughFilter"
     - "NUMATopologyFilter"
     - "AggregateInstanceExtraSpecsFilter"
